# Generated by Django 4.1.3 on 2022-11-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymodel',
            old_name='city',
            new_name='name',
        ),
    ]
