# Generated by Django 4.1.3 on 2022-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
