# Generated by Django 4.1.3 on 2022-11-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_city_citymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.citymodel'),
        ),
    ]
