# Generated by Django 4.1.3 on 2022-12-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categorymodel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='city',
        ),
    ]
