# Generated by Django 4.1.3 on 2023-05-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='auther',
        ),
    ]
