# Generated by Django 4.1.3 on 2022-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_categorymodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
