# Generated by Django 4.1.3 on 2022-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contactmodel_phone2_contactmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
