# Generated by Django 4.1.3 on 2022-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
