# Generated by Django 4.1.3 on 2023-05-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contactmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='city', to='core.citymodel'),
        ),
    ]
